export const GET_MANDAL_LIST = 'GET_MANDAL_LIST';
export const GET_MANDAL_LIST_REQUEST = 'GET_MANDAL_LIST_REQUEST';
export const GET_MANDAL_LIST_SUCCESS = 'GET_MANDAL_LIST_SUCCESS';
export const GET_MANDAL_LIST_FAILURE = 'GET_MANDAL_LIST_FAILURE';